version: '3.8'
services:
  dev-db:
    image: mysql:latest
    container_name: dev-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3366:3306'
    networks:
      - dev-node
networks:
  dev-node:
